logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "module"                                                   # 'both', 'apk' or 'module'
excluded-patches = ""                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = "client-spoof copy-video-url custom-video-buffer custom-video-speed disable-auto-captions disable-shorts-on-startup downloads general-ads hdr-auto-brightness hide-get-premium minimized-playback old-quality-layout open-links-externally remember-playback-speed remember-video-quality sponsorblock return-youtube-dislike theme spoof-app-version video-ads wide-searchbar"                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "18.16.37"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default and only applies included-patches
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"
