logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "module"                                                   # 'both', 'apk' or 'module'
excluded-patches = "comments custom-branding disable-fullscreen-panels disable-player-popup-panels enable-debugging hide-album-cards hide-artist-card hide-autoplay-button hide-breaking-news-shelf hide-captions-button hide-cast-button hide-crowdfunding-box	hide-email-address hide-endscreen-cards hide-floating-microphone-button hide-info-cards hide-player-buttons hide-player-overlay hide-seekbar hide-timestamp hide-video-action-buttons premium-heading swipe-controls vanced-microg-support tablet-mini-player "                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = ""                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "18.16.37"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default and only applies included-patches
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"
